apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-apps # Your root app name
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sutrisnaanjoy19/Ecommerce-k8s-minikube.git
    targetRevision: HEAD
    path: Argocd/applications # <--- This ensures it finds simple-frontend-default-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true